"use client";

import {
  BarChart3,
  BrainCircuit,
  Building2,
  Calculator,
  CalendarDays,
  Camera,
  ClipboardCheck,
  Clock,
  FileCheck,
  FileOutput,
  FileSpreadsheet,
  FileText,
  FolderOpen,
  Gauge,
  Layers,
  type LucideIcon,
  MapPin,
  PackageSearch,
  Palette,
  PenLine,
  Pipette,
  Receipt,
  Route,
  Ruler,
  Scan,
  Shield,
  ShoppingCart,
  Smartphone,
  Thermometer,
  Users,
  Wrench,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  BarChart3,
  BrainCircuit,
  Building2,
  Calculator,
  CalendarDays,
  Camera,
  ClipboardCheck,
  Clock,
  FileCheck,
  FileOutput,
  FileSpreadsheet,
  FileText,
  FolderOpen,
  Gauge,
  Layers,
  MapPin,
  PackageSearch,
  Palette,
  PenLine,
  Pipette,
  Receipt,
  Route,
  Ruler,
  Scan,
  Shield,
  ShoppingCart,
  Smartphone,
  Thermometer,
  Users,
  Wrench,
};

export function TradeFeatureIcon({ name }: { name: string }) {
  const Icon = iconMap[name];
  if (!Icon) return null;
  return <Icon className="h-4 w-4 text-primary" strokeWidth={1.8} aria-hidden="true" />;
}
