import type { Metadata } from "next";
import brandLogo from "@repo/brand/logo";
import { geistMono, geistSans } from "@repo/fonts/geist";
import { Providers } from "@repo/ui/providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: brandLogo.src, type: "image/png", sizes: "512x512" }],
    apple: [{ url: brandLogo.src, type: "image/png", sizes: "180x180" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
